import Config

# Set environment
config :hermes, :env, :prod

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :hermes, HermesWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# File logging - rotate at 10 MB, keep last 5 files
config :kernel,
  logger: [
    {:handler, :file_log, :logger_std_h,
     %{
       config: %{
         type: :file,
         file: ~c"/var/log/hermes/app.log",
         max_no_bytes: 10_485_760,
         max_no_files: 5
       },
       formatter: Logger.Formatter.new(colors: [enabled: false]),
       level: :info
     }}
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
